/** @type {import('./types.js').QmsModuleDefinition[]} */
export const QMS_MODULES = [
  {
    moduleKey: 'document-control',
    displayName: 'Document Control',
    description: 'Controlled documents, revisions, approvals, effective dating, and periodic review.',
    commonEntities: ['Document', 'DocumentRevision', 'DocumentAssignment', 'DocumentSignature', 'DocumentHistory'],
    commonRoles: ['Author', 'Reviewer', 'Approver', 'Quality Release', 'System Admin'],
    commonStatuses: ['DRAFT', 'IN_REVIEW', 'AWAITING_APPROVAL', 'APPROVED', 'EFFECTIVE', 'OBSOLETE', 'ARCHIVED'],
    commonWorkflowPatterns: ['Review then approve', 'Quality release gate', 'Periodic review cycle', 'Supersedes linkage'],
    commonAuditRequirements: ['Immutable history', 'Who/when/why on transitions', 'Hash or fingerprint on sign'],
    commonTrainingLinkageRules: ['Training assignment on EFFECTIVE', 'Read-and-understood for critical SOPs'],
    commonNotificationPatterns: ['Assignment due', 'Approval pending', 'Periodic review overdue'],
    commonUIAreas: ['src/pages/DocumentControl.tsx', 'src/pages/DocumentDetail.tsx', 'server/src/documents.js'],
    commonSchemaPatterns: ['documents table versioning', 'document_history', 'document_assignments'],
    commonRisks: ['Accidental overwrite of effective content', 'Broken supersedes chain', 'Missing signature meaning'],
    validationHints: ['Unique (documentId, version)', 'Status machine enforced server-side', 'E-sign before EFFECTIVE'],
  },
  {
    moduleKey: 'training',
    displayName: 'Training & Competency',
    description: 'Training modules, assignments, completion, overdue handling, and competency evidence.',
    commonEntities: ['TrainingModule', 'UserTrainingRecord'],
    commonRoles: ['Trainer', 'Manager', 'Employee', 'Quality'],
    commonStatuses: ['ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE'],
    commonWorkflowPatterns: ['Assign on effective document', 'Completion attestation', 'Recurring training'],
    commonAuditRequirements: ['Completion timestamps', 'Score evidence if applicable', 'Trainer sign-off when required'],
    commonTrainingLinkageRules: ['Module tied to controlled document version', 'Re-assign when document revises'],
    commonNotificationPatterns: ['Due soon', 'Overdue', 'Re-certification'],
    commonUIAreas: ['src/pages/TrainingCompetency.tsx', 'server/src/training.js'],
    commonSchemaPatterns: ['user_training_records', 'training_modules.document_id'],
    commonRisks: ['Stale assignments after document revision', 'Overdue not escalated', 'Missing competency mapping'],
    validationHints: ['Status transitions', 'Due date required', 'Completion requires authenticated user'],
  },
  {
    moduleKey: 'capa',
    displayName: 'CAPA',
    description: 'Corrective and preventive actions, tasks, containment, RCA, effectiveness, closure.',
    commonEntities: ['CAPA', 'CapaTask', 'CapaHistory', 'CapaSignature'],
    commonRoles: ['Owner', 'Assignee', 'Approver', 'Quality'],
    commonStatuses: ['DRAFT', 'OPEN', 'CONTAINMENT', 'INVESTIGATION', 'PLAN_APPROVAL', 'IMPLEMENTATION', 'EFFECTIVENESS_CHECK', 'PENDING_CLOSURE', 'CLOSED'],
    commonWorkflowPatterns: ['RCA before plan', 'Plan approval', 'Effectiveness check', 'Closure review'],
    commonAuditRequirements: ['History entries per state change', 'Signature on closure', 'Evidence attachments'],
    commonTrainingLinkageRules: ['Training if CAPA changes procedures', 'Task-level competency when assigned'],
    commonNotificationPatterns: ['Task due', 'Approval pending', 'Effectiveness window'],
    commonUIAreas: ['src/pages/capas', 'server/src/capas.js'],
    commonSchemaPatterns: ['capas', 'capa_tasks', 'capa_history'],
    commonRisks: ['Skipping RCA', 'Weak effectiveness evidence', 'Open actions without owners'],
    validationHints: ['Owner required for OPEN', 'Effectiveness waiver requires justification', 'Task ordering'],
  },
  {
    moduleKey: 'change-control',
    displayName: 'Change Control',
    description: 'Controlled changes to process, documents, software, infrastructure, with approvals.',
    commonEntities: ['ChangeControl', 'ChangeControlTask', 'ChangeControlHistory', 'ChangeControlSignature'],
    commonRoles: ['Initiator', 'Owner', 'Approver', 'Implementer'],
    commonStatuses: ['DRAFT', 'SUBMITTED', 'REVIEW', 'APPROVAL', 'IMPLEMENTATION', 'EFFECTIVENESS', 'PENDING_CLOSURE', 'CLOSED'],
    commonWorkflowPatterns: ['Impact assessment', 'Segregated approval', 'Implementation evidence', 'Effectiveness'],
    commonAuditRequirements: ['Decision rationale', 'Linked documents/CAPA', 'E-sign on approval/closure'],
    commonTrainingLinkageRules: ['Training tasks in plan', 'Notify affected roles on EFFECTIVE'],
    commonNotificationPatterns: ['Approval queue', 'Implementation due', 'Effectiveness due'],
    commonUIAreas: ['src/pages/ChangeControl.tsx', 'server/src/changeControls.js'],
    commonSchemaPatterns: ['change_controls', 'change_control_tasks'],
    commonRisks: ['Unapproved production deploy', 'Missing impact assessment', 'Effectiveness not measurable'],
    validationHints: ['Risk level captured', 'Owner on active states', 'E-sign configuration respected'],
  },
  {
    moduleKey: 'supplier-quality',
    displayName: 'Supplier Quality',
    description: 'Supplier qualification, audits, scorecards, SCARs, and restricted suppliers.',
    commonEntities: ['Supplier', 'SupplierAudit', 'SCAR', 'QualificationRecord'],
    commonRoles: ['SQE', 'Approver', 'Procurement'],
    commonStatuses: ['PROSPECT', 'QUALIFIED', 'ON_PROBATION', 'DISQUALIFIED'],
    commonWorkflowPatterns: ['Initial qualification', 'Requalification cycle', 'SCAR response', 'Restricted use'],
    commonAuditRequirements: ['Audit evidence retention', 'Decision log for status changes'],
    commonTrainingLinkageRules: ['SQE training on supplier processes', 'Read SOP for restricted handling'],
    commonNotificationPatterns: ['Audit due', 'SCAR response due', 'Certificate expiry'],
    commonUIAreas: ['src/pages/SupplierQuality.tsx'],
    commonSchemaPatterns: ['supplier-related tables (as implemented)', 'file attachments to supplier records'],
    commonRisks: ['Using unqualified supplier', 'Stale certificates', 'SCAR recurrence without RCA'],
    validationHints: ['Status gates for PO release (if integrated)', 'Documented criteria for qualification'],
  },
  {
    moduleKey: 'audit-management',
    displayName: 'Audit Management',
    description: 'Audit programs, findings, responses, and linkage to CAPA.',
    commonEntities: ['Audit', 'AuditFinding'],
    commonRoles: ['Lead Auditor', 'Auditee', 'Quality', 'CAPA Owner'],
    commonStatuses: ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'],
    commonWorkflowPatterns: ['Opening meeting', 'Evidence collection', 'Finding disposition', 'CAPA linkage'],
    commonAuditRequirements: ['Finding severity', 'Response due dates', 'Evidence of closure'],
    commonTrainingLinkageRules: ['Training on audit-derived procedure changes'],
    commonNotificationPatterns: ['Finding assigned', 'Response overdue', 'CAPA linkage required'],
    commonUIAreas: ['src/pages/AuditManagement.tsx', 'src/pages/AuditDetail.tsx', 'server/src/audits.js'],
    commonSchemaPatterns: ['audits', 'audit_findings', 'linked_capa_id'],
    commonRisks: ['Findings without owners', 'Severity misclassification', 'Untraceable evidence'],
    validationHints: ['CAPA link for major/critical', 'Response due enforcement'],
  },
  {
    moduleKey: 'deviation',
    displayName: 'Deviation',
    description: 'Planned or unplanned deviations, investigations, disposition, and product impact.',
    commonEntities: ['Deviation', 'DeviationTask', 'DeviationInvestigation'],
    commonRoles: ['Initiator', 'QA', 'Approver', 'Manufacturing'],
    commonStatuses: ['OPEN', 'UNDER_INVESTIGATION', 'PENDING_APPROVAL', 'CLOSED'],
    commonWorkflowPatterns: ['Risk-based classification', 'Investigation plan', 'Disposition approval'],
    commonAuditRequirements: ['Rationale for accept/reject', 'Batch/lot traceability', 'Timestamps'],
    commonTrainingLinkageRules: ['Training if deviation changes controlled practice'],
    commonNotificationPatterns: ['Investigation due', 'Approval pending', 'Product hold/release'],
    commonUIAreas: ['(deviation UI routes as implemented)', 'server routes for deviations if present'],
    commonSchemaPatterns: ['deviation tables (additive when introduced)', 'links to lot/batch records'],
    commonRisks: ['Unreviewed repeat deviations', 'Insufficient product impact assessment'],
    validationHints: ['Mandatory investigation fields by class', 'Segregation of approval vs execution'],
  },
  {
    moduleKey: 'risk-management',
    displayName: 'Risk Management',
    description: 'Risk registers, assessments, mitigations, and review cadence.',
    commonEntities: ['Risk', 'RiskAssessment', 'RiskMitigation', 'RiskReview'],
    commonRoles: ['Risk Owner', 'Approver', 'Executive'],
    commonStatuses: ['IDENTIFIED', 'ASSESSED', 'MITIGATING', 'ACCEPTED', 'CLOSED'],
    commonWorkflowPatterns: ['Score and prioritize', 'Mitigation plan', 'Residual risk acceptance'],
    commonAuditRequirements: ['Versioned assessment', 'Approver on acceptance', 'Evidence of controls'],
    commonTrainingLinkageRules: ['Training when risk changes operational controls'],
    commonNotificationPatterns: ['Review due', 'Mitigation overdue', 'Escalation thresholds'],
    commonUIAreas: ['src/pages/RiskManagement.tsx'],
    commonSchemaPatterns: ['risk register tables (as implemented)', 'links to change/CAPA'],
    commonRisks: ['Stale risk scores', 'Accepted risks without monitoring', 'Missing linkage to changes'],
    validationHints: ['Numeric scoring consistency', 'Residual risk rationale', 'Review frequency'],
  },
];
