/** @type {import('./types.js').WorkflowTemplateDefinition[]} */
export const WORKFLOW_TEMPLATES = [
  {
    templateKey: 'controlled-document-review',
    templateName: 'Controlled Document Review',
    targetModules: ['document-control'],
    objective: 'Move a controlled document from draft through review, approval, and controlled release.',
    defaultStates: [
      { stateKey: 'draft', label: 'Draft authoring', sortOrder: 0 },
      { stateKey: 'in_review', label: 'Technical / quality review', sortOrder: 1 },
      { stateKey: 'pending_approval', label: 'Pending approval', sortOrder: 2 },
      { stateKey: 'pending_quality_release', label: 'Pending quality release', sortOrder: 3 },
      { stateKey: 'effective', label: 'Effective', sortOrder: 4 },
    ],
    defaultTransitions: [
      { from: 'draft', to: 'in_review', label: 'Submit for review', rolesJson: ['Reviewer'] },
      { from: 'in_review', to: 'pending_approval', label: 'Review complete', rolesJson: ['Reviewer'] },
      { from: 'pending_approval', to: 'pending_quality_release', label: 'Approved', rolesJson: ['Approver'] },
      { from: 'pending_quality_release', to: 'effective', label: 'Released', rolesJson: ['Quality Release'] },
    ],
    defaultRoles: ['Reviewer', 'Approver', 'Quality Release'],
    approvalModel: 'sequential',
    auditRequirements: ['Immutable document history', 'Signature meaning captured', 'Effective date rationale'],
    notificationRules: ['Reviewer assignment', 'Approver queue', 'Release notification to training owner'],
    trainingLinkageRules: ['Assign training when document becomes EFFECTIVE', 'Obsolete prior training if superseded'],
    uiRecommendations: ['Document detail approvals panel', 'Assignment due dates', 'Status badges aligned to enum'],
    schemaRecommendations: ['Preserve additive columns for review metadata', 'Avoid destructive enum changes'],
  },
  {
    templateKey: 'training-assignment-effective-date',
    templateName: 'Training Assignment on Effective Date',
    targetModules: ['training', 'document-control'],
    objective: 'Assign and track training when a governing document becomes effective.',
    defaultStates: [
      { stateKey: 'pending_effective', label: 'Awaiting governing document effective', sortOrder: 0 },
      { stateKey: 'assigned', label: 'Training assigned', sortOrder: 1 },
      { stateKey: 'in_progress', label: 'In progress', sortOrder: 2 },
      { stateKey: 'completed', label: 'Completed', sortOrder: 3 },
      { stateKey: 'overdue', label: 'Overdue', sortOrder: 4 },
    ],
    defaultTransitions: [
      { from: 'pending_effective', to: 'assigned', label: 'Document effective → assign', rolesJson: ['System', 'Quality'] },
      { from: 'assigned', to: 'in_progress', label: 'Learner started', rolesJson: ['Employee'] },
      { from: 'in_progress', to: 'completed', label: 'Completed / scored', rolesJson: ['Employee', 'Trainer'] },
      { from: 'assigned', to: 'overdue', label: 'Past due (automated)', rolesJson: ['System'] },
    ],
    defaultRoles: ['Quality', 'Manager', 'Employee', 'Trainer'],
    approvalModel: 'lightweight',
    auditRequirements: ['Completion timestamp', 'Module version linkage', 'Overdue audit trail'],
    notificationRules: ['Due soon', 'Overdue reminders', 'Manager escalation'],
    trainingLinkageRules: ['Module must reference effective document version', 'Re-open on major revision'],
    uiRecommendations: ['Training dashboard filters', 'Document-to-training trace link'],
    schemaRecommendations: ['Nullable completion fields until done', 'Index by user + status for overdue scans'],
  },
  {
    templateKey: 'capa-lifecycle',
    templateName: 'CAPA Lifecycle',
    targetModules: ['capa'],
    objective: 'Contain, investigate, plan, implement, verify effectiveness, and close a CAPA with evidence.',
    defaultStates: [
      { stateKey: 'open', label: 'Open / triage', sortOrder: 0 },
      { stateKey: 'containment', label: 'Containment', sortOrder: 1 },
      { stateKey: 'investigation', label: 'Investigation / RCA', sortOrder: 2 },
      { stateKey: 'plan_approval', label: 'Plan approval', sortOrder: 3 },
      { stateKey: 'implementation', label: 'Implementation', sortOrder: 4 },
      { stateKey: 'effectiveness', label: 'Effectiveness check', sortOrder: 5 },
      { stateKey: 'closure', label: 'Pending closure', sortOrder: 6 },
      { stateKey: 'closed', label: 'Closed', sortOrder: 7 },
    ],
    defaultTransitions: [
      { from: 'open', to: 'containment', label: 'Containment required', rolesJson: ['Owner'] },
      { from: 'containment', to: 'investigation', label: 'Containment complete', rolesJson: ['Owner'] },
      { from: 'investigation', to: 'plan_approval', label: 'RCA complete', rolesJson: ['Quality'] },
      { from: 'plan_approval', to: 'implementation', label: 'Plan approved', rolesJson: ['Approver'] },
      { from: 'implementation', to: 'effectiveness', label: 'Actions implemented', rolesJson: ['Owner'] },
      { from: 'effectiveness', to: 'closure', label: 'Effectiveness verified', rolesJson: ['Quality'] },
      { from: 'closure', to: 'closed', label: 'Closure approved', rolesJson: ['Approver'] },
    ],
    defaultRoles: ['Owner', 'Assignee', 'Quality', 'Approver'],
    approvalModel: 'gated',
    auditRequirements: ['History per transition', 'Effectiveness evidence or waiver with justification', 'Signatures on closure'],
    notificationRules: ['Task due', 'Approval pending', 'Effectiveness window'],
    trainingLinkageRules: ['Training tasks when procedures change'],
    uiRecommendations: ['CAPA detail tabs for RCA, actions, effectiveness', 'Signature modals reuse QMS patterns'],
    schemaRecommendations: ['Additive JSON fields for RCA if needed', 'Avoid dropping history tables'],
  },
  {
    templateKey: 'change-control-approval',
    templateName: 'Change Control Approval',
    targetModules: ['change-control'],
    objective: 'Assess impact, approve, implement, verify effectiveness, and close a controlled change.',
    defaultStates: [
      { stateKey: 'draft', label: 'Draft', sortOrder: 0 },
      { stateKey: 'submitted', label: 'Submitted', sortOrder: 1 },
      { stateKey: 'review', label: 'Impact review', sortOrder: 2 },
      { stateKey: 'approval', label: 'Approval', sortOrder: 3 },
      { stateKey: 'implementation', label: 'Implementation', sortOrder: 4 },
      { stateKey: 'effectiveness', label: 'Effectiveness', sortOrder: 5 },
      { stateKey: 'closed', label: 'Closed', sortOrder: 6 },
    ],
    defaultTransitions: [
      { from: 'draft', to: 'submitted', label: 'Submit', rolesJson: ['Initiator'] },
      { from: 'submitted', to: 'review', label: 'Start review', rolesJson: ['Owner'] },
      { from: 'review', to: 'approval', label: 'Review complete', rolesJson: ['Owner'] },
      { from: 'approval', to: 'implementation', label: 'Approved', rolesJson: ['Approver'] },
      { from: 'implementation', to: 'effectiveness', label: 'Implemented', rolesJson: ['Owner'] },
      { from: 'effectiveness', to: 'closed', label: 'Effectiveness accepted', rolesJson: ['Approver'] },
    ],
    defaultRoles: ['Initiator', 'Owner', 'Approver'],
    approvalModel: 'segregated',
    auditRequirements: ['Linked documents/CAPA references', 'Approval rationale', 'Implementation evidence'],
    notificationRules: ['Approval queue', 'Implementation milestones', 'Effectiveness due'],
    trainingLinkageRules: ['Training tasks embedded in change plan'],
    uiRecommendations: ['Change detail timeline', 'Linked entities panel'],
    schemaRecommendations: ['Additive fields for verification summaries', 'Index by status for queues'],
  },
  {
    templateKey: 'supplier-qualification-review',
    templateName: 'Supplier Qualification Review',
    targetModules: ['supplier-quality'],
    objective: 'Qualify or requalify a supplier with documented criteria and audit evidence.',
    defaultStates: [
      { stateKey: 'intake', label: 'Intake / scope', sortOrder: 0 },
      { stateKey: 'assessment', label: 'Assessment / audit', sortOrder: 1 },
      { stateKey: 'disposition', label: 'Disposition decision', sortOrder: 2 },
      { stateKey: 'qualified', label: 'Qualified', sortOrder: 3 },
    ],
    defaultTransitions: [
      { from: 'intake', to: 'assessment', label: 'Start assessment', rolesJson: ['SQE'] },
      { from: 'assessment', to: 'disposition', label: 'Assessment complete', rolesJson: ['SQE'] },
      { from: 'disposition', to: 'qualified', label: 'Approve qualification', rolesJson: ['Approver'] },
    ],
    defaultRoles: ['SQE', 'Approver', 'Procurement'],
    approvalModel: 'committee_optional',
    auditRequirements: ['Audit report retention', 'Criteria checklist', 'Decision log'],
    notificationRules: ['Certificate expiry', 'Requalification due'],
    trainingLinkageRules: ['SQE procedure training references'],
    uiRecommendations: ['Supplier profile tabs', 'Evidence attachments'],
    schemaRecommendations: ['Prefer additive supplier metadata columns', 'Soft-delete vs hard-delete policy'],
  },
  {
    templateKey: 'internal-audit-lifecycle',
    templateName: 'Internal Audit Lifecycle',
    targetModules: ['audit-management'],
    objective: 'Plan, execute, record findings, and drive responses with traceability.',
    defaultStates: [
      { stateKey: 'scheduled', label: 'Scheduled', sortOrder: 0 },
      { stateKey: 'in_progress', label: 'In progress', sortOrder: 1 },
      { stateKey: 'reporting', label: 'Reporting', sortOrder: 2 },
      { stateKey: 'completed', label: 'Completed', sortOrder: 3 },
    ],
    defaultTransitions: [
      { from: 'scheduled', to: 'in_progress', label: 'Start audit', rolesJson: ['Lead Auditor'] },
      { from: 'in_progress', to: 'reporting', label: 'Fieldwork complete', rolesJson: ['Lead Auditor'] },
      { from: 'reporting', to: 'completed', label: 'Final report issued', rolesJson: ['Quality'] },
    ],
    defaultRoles: ['Lead Auditor', 'Auditee', 'Quality'],
    approvalModel: 'lightweight',
    auditRequirements: ['Finding codes', 'Severity', 'Response due', 'CAPA linkage for majors'],
    notificationRules: ['Response due', 'CAPA required'],
    trainingLinkageRules: ['Training if procedures change due to findings'],
    uiRecommendations: ['Audit detail findings table', 'CAPA link picker'],
    schemaRecommendations: ['Finding status indexes', 'FK integrity to CAPA optional'],
  },
  {
    templateKey: 'deviation-investigation',
    templateName: 'Deviation Investigation',
    targetModules: ['deviation'],
    objective: 'Classify, investigate, disposition, and approve product/process impact.',
    defaultStates: [
      { stateKey: 'opened', label: 'Opened', sortOrder: 0 },
      { stateKey: 'investigation', label: 'Investigation', sortOrder: 1 },
      { stateKey: 'pending_approval', label: 'Pending approval', sortOrder: 2 },
      { stateKey: 'closed', label: 'Closed', sortOrder: 3 },
    ],
    defaultTransitions: [
      { from: 'opened', to: 'investigation', label: 'Classify & investigate', rolesJson: ['QA'] },
      { from: 'investigation', to: 'pending_approval', label: 'Disposition proposed', rolesJson: ['QA'] },
      { from: 'pending_approval', to: 'closed', label: 'Approved closure', rolesJson: ['Approver'] },
    ],
    defaultRoles: ['Initiator', 'QA', 'Approver'],
    approvalModel: 'risk_based',
    auditRequirements: ['Lot/batch trace', 'Rationale for accept/reject', 'Timestamps'],
    notificationRules: ['Hold/release notifications if applicable'],
    trainingLinkageRules: ['Training if practice changes'],
    uiRecommendations: ['Deviation detail impact matrix', 'Attachment evidence list'],
    schemaRecommendations: ['Additive deviation tables when introduced', 'Non-destructive enums'],
  },
  {
    templateKey: 'risk-assessment-review',
    templateName: 'Risk Assessment Review',
    targetModules: ['risk-management'],
    objective: 'Identify, assess, mitigate, and periodically review risks with acceptance governance.',
    defaultStates: [
      { stateKey: 'identified', label: 'Identified', sortOrder: 0 },
      { stateKey: 'assessed', label: 'Assessed', sortOrder: 1 },
      { stateKey: 'mitigating', label: 'Mitigating', sortOrder: 2 },
      { stateKey: 'accepted', label: 'Accepted / monitored', sortOrder: 3 },
    ],
    defaultTransitions: [
      { from: 'identified', to: 'assessed', label: 'Assessment complete', rolesJson: ['Risk Owner'] },
      { from: 'assessed', to: 'mitigating', label: 'Mitigation in flight', rolesJson: ['Risk Owner'] },
      { from: 'mitigating', to: 'accepted', label: 'Residual accepted', rolesJson: ['Approver'] },
    ],
    defaultRoles: ['Risk Owner', 'Approver', 'Executive'],
    approvalModel: 'acceptance_gate',
    auditRequirements: ['Versioned assessment', 'Monitoring evidence', 'Approver on acceptance'],
    notificationRules: ['Review cadence', 'Escalation thresholds'],
    trainingLinkageRules: ['Training when controls change'],
    uiRecommendations: ['Risk register scoring UI', 'Mitigation task linkage'],
    schemaRecommendations: ['Additive scoring fields', 'Historical snapshots JSON'],
  },
];
